choco install googlechrome -y
choco install 7zip.install -y
choco install notepadplusplus.install -y
choco install git.install -y
choco install autoit.install -y
choco install azure-cli -y
choco install azure-pipelines-agent -y
choco install microsoftazurestorageexplorer -y
choco install procexp -y
choco install procmon -y
choco install selenium -y
choco install selenium-chrome-driver -y
choco install vscode -y
choco install chocolatey-vscode -y
choco install vscode-ansible -y
choco install vscode-yaml -y
choco install vscode-python -y
choco install vscode-azure-deploy -y
choco install sql-server-management-studio -y
choco install sysinternals -y
choco install winmerge -y 
choco install postman -y
choco install wireshark -y
choco install python --version=3.8.5.20200721 -y
